In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_excel(r"C:\Users\shree\OneDrive\Desktop\IR Project Working Directory\final_processed_results.xlsx")
df

,Unnamed: 0,index,product_name,product_type,review_text,rating,initial_sentiment,normal_sentiment_score,normal_sentiment,rating_by_normal_sentiment,aspect_ratings
0,0,0,sphere,books,sphere michael crichton excellant novel certai...,5,positive,0.9231,positive,5,"{'novel': 3, 'misssion': 3, 'mile': 3, 'spacec..."
1,1,1,healing from the heart,books,dr oz accomplished heart surgeon field cardiac...,4,positive,0.9300,positive,5,"{'transplantation': 4, 'epilogue': 4, 'medicin..."
2,2,2,mythology,books,gorgeous artwork comic books contains extraord...,5,positive,0.9118,positive,5,"{'books': 4, 'artwork': 3}"
3,3,4,guns germs and steel,books,going short sweet review many others commented...,5,positive,0.9912,positive,5,"{'review': 4, 'others': 2, 'value': 3, 'though..."
4,4,5,worlds fairs and the end of progress,books,since worlds fair fanatic read almost everythi...,4,positive,0.9633,positive,5,"{'worlds': 4, 'read': 4, 'book_author': 3, 'er..."
...,...,...,...,...,...,...,...,...,...,...,...
60984,60984,72632,mr coffee cocomotion hot chocolate maker,kitchen & housewares,four children plus lots friends make hot choco...,5,positive,0.9246,positive,5,"{'chocolate': 3, 'stand': 3, 'hot': 3, 'compla..."
60985,60985,72633,mr coffee cocomotion hot chocolate maker,kitchen & housewares,perfect little machine love cocomotion perfect...,5,positive,0.9745,positive,5,"{'cocomotion': 3, 'cold': 4, 'dodad': 3, 'mix'..."
60986,60986,72634,mr coffee cocomotion hot chocolate maker,kitchen & housewares,gave gift told makes great cup hot chocolate,5,positive,0.7906,positive,5,{'cup': 4}
60987,60987,72636,mr coffee cocomotion hot chocolate maker,kitchen & housewares,got little machine first came market fan presw...,5,positive,0.9719,positive,5,"{'machine': 3, 'chocolate_mixes': 3, 'fashion_..."
60988,60988,72637,mr coffee cocomotion hot chocolate maker,kitchen & housewares,mom bought christmas well name tag im positive...,5,positive,0.9899,positive,5,"{'daughters_lol': 3, 'glad': 4, 'milk': 3, 'sa..."

In [3]:
# Remove two columns name is 'C' and 'D'
df.drop(['Unnamed: 0', 'index'], axis=1, inplace = True)
df

,product_name,product_type,review_text,rating,initial_sentiment,normal_sentiment_score,normal_sentiment,rating_by_normal_sentiment,aspect_ratings
0,sphere,books,sphere michael crichton excellant novel certai...,5,positive,0.9231,positive,5,"{'novel': 3, 'misssion': 3, 'mile': 3, 'spacec..."
1,healing from the heart,books,dr oz accomplished heart surgeon field cardiac...,4,positive,0.9300,positive,5,"{'transplantation': 4, 'epilogue': 4, 'medicin..."
2,mythology,books,gorgeous artwork comic books contains extraord...,5,positive,0.9118,positive,5,"{'books': 4, 'artwork': 3}"
3,guns germs and steel,books,going short sweet review many others commented...,5,positive,0.9912,positive,5,"{'review': 4, 'others': 2, 'value': 3, 'though..."
4,worlds fairs and the end of progress,books,since worlds fair fanatic read almost everythi...,4,positive,0.9633,positive,5,"{'worlds': 4, 'read': 4, 'book_author': 3, 'er..."
...,...,...,...,...,...,...,...,...,...
60984,mr coffee cocomotion hot chocolate maker,kitchen & housewares,four children plus lots friends make hot choco...,5,positive,0.9246,positive,5,"{'chocolate': 3, 'stand': 3, 'hot': 3, 'compla..."
60985,mr coffee cocomotion hot chocolate maker,kitchen & housewares,perfect little machine love cocomotion perfect...,5,positive,0.9745,positive,5,"{'cocomotion': 3, 'cold': 4, 'dodad': 3, 'mix'..."
60986,mr coffee cocomotion hot chocolate maker,kitchen & housewares,gave gift told makes great cup hot chocolate,5,positive,0.7906,positive,5,{'cup': 4}
60987,mr coffee cocomotion hot chocolate maker,kitchen & housewares,got little machine first came market fan presw...,5,positive,0.9719,positive,5,"{'machine': 3, 'chocolate_mixes': 3, 'fashion_..."
60988,mr coffee cocomotion hot chocolate maker,kitchen & housewares,mom bought christmas well name tag im positive...,5,positive,0.9899,positive,5,"{'daughters_lol': 3, 'glad': 4, 'milk': 3, 'sa..."

In [4]:
type(df['aspect_ratings'][0])

str

In [5]:
# Converting 'aspect_ratings' column from type string to dictionary 
# define a function to convert the string to a dictionary
import ast 
def str_to_dict(s):
    return ast.literal_eval(s)

# apply the function to the column
df['aspect_ratings'] = df['aspect_ratings'].apply(str_to_dict)

In [6]:
type(df['aspect_ratings'][0])

dict

In [7]:
# use groupby and transform to add a new column with the count of rows in each group
import numpy as np
df['count'] = df.groupby('product_name')['product_name'].transform('count')

# replace NaN values with 0
df['count'] = df['count'].fillna(0)

# convert to integer
df['count'] = df['count'].astype(np.int64)
df

,product_name,product_type,review_text,rating,initial_sentiment,normal_sentiment_score,normal_sentiment,rating_by_normal_sentiment,aspect_ratings,count
0,sphere,books,sphere michael crichton excellant novel certai...,5,positive,0.9231,positive,5,"{'novel': 3, 'misssion': 3, 'mile': 3, 'spacec...",1
1,healing from the heart,books,dr oz accomplished heart surgeon field cardiac...,4,positive,0.9300,positive,5,"{'transplantation': 4, 'epilogue': 4, 'medicin...",1
2,mythology,books,gorgeous artwork comic books contains extraord...,5,positive,0.9118,positive,5,"{'books': 4, 'artwork': 3}",1
3,guns germs and steel,books,going short sweet review many others commented...,5,positive,0.9912,positive,5,"{'review': 4, 'others': 2, 'value': 3, 'though...",9
4,worlds fairs and the end of progress,books,since worlds fair fanatic read almost everythi...,4,positive,0.9633,positive,5,"{'worlds': 4, 'read': 4, 'book_author': 3, 'er...",1
...,...,...,...,...,...,...,...,...,...,...
60984,mr coffee cocomotion hot chocolate maker,kitchen & housewares,four children plus lots friends make hot choco...,5,positive,0.9246,positive,5,"{'chocolate': 3, 'stand': 3, 'hot': 3, 'compla...",6
60985,mr coffee cocomotion hot chocolate maker,kitchen & housewares,perfect little machine love cocomotion perfect...,5,positive,0.9745,positive,5,"{'cocomotion': 3, 'cold': 4, 'dodad': 3, 'mix'...",6
60986,mr coffee cocomotion hot chocolate maker,kitchen & housewares,gave gift told makes great cup hot chocolate,5,positive,0.7906,positive,5,{'cup': 4},6
60987,mr coffee cocomotion hot chocolate maker,kitchen & housewares,got little machine first came market fan presw...,5,positive,0.9719,positive,5,"{'machine': 3, 'chocolate_mixes': 3, 'fashion_...",6
60988,mr coffee cocomotion hot chocolate maker,kitchen & housewares,mom bought christmas well name tag im positive...,5,positive,0.9899,positive,5,"{'daughters_lol': 3, 'glad': 4, 'milk': 3, 'sa...",6

In [8]:
# Merging similar aspects for similar products
from collections import defaultdict
aspects_dict = defaultdict(lambda: {'sum': 0, 'count': 0, 'products': set()})
for index, row in df.iterrows():
    for k, v in row['aspect_ratings'].items():
        aspects_dict[k]['sum'] += v
        aspects_dict[k]['count'] += 1
        aspects_dict[k]['products'].add(row['product_name'])

aspects_avg_dict = {}
for k, v in aspects_dict.items():
    if len(v['products']) == 1:
        aspects_avg_dict[k] = v['sum']
    else:
        aspects_avg_dict[k] = v['sum']/v['count']

df_grouped = df.groupby('product_name').agg({'count':lambda x: x.mode().iloc[0],'product_type': lambda x: x.mode().iloc[0], 'rating':'mean', 'normal_sentiment_score':'mean', 'rating_by_normal_sentiment':'mean', 'initial_sentiment':lambda x: x.mode().iloc[0], 'normal_sentiment':lambda x: x.mode().iloc[0], 'aspect_ratings': lambda x: {k:v for k,v in aspects_avg_dict.items() if k in x.values[0].keys()}})
# df_grouped = df.groupby('product_name').agg({'product_type': lambda x: x.mode().iloc[0], 
#                                             'rating':'mean', 
#                                             'normal_sentiment_score':'mean', 
#                                             'rating_by_normal_sentiment':'mean', 
#                                             'initial_sentiment':lambda x: x.mode().iloc[0], 
#                                             'normal_sentiment':lambda x: x.mode().iloc[0], 
#                                             'aspect_ratings': lambda x: {k:v for k,v in aspects_avg_dict.items() if k in x.values[0].keys()}})\
#                .reset_index()\
#                .assign(count_rows=lambda x: x.groupby('product_name')['product_name'].transform('count'))

df_grouped

,count,product_type,rating,normal_sentiment_score,rating_by_normal_sentiment,initial_sentiment,normal_sentiment,aspect_ratings
product_name,,,,,,,,
089 deep stainless steel mixing bowl set 3pc,1,kitchen & housewares,5.000000,0.680100,5.000000,positive,positive,{'serve': 3.1818181818181817}
1 doz red roses,6,kitchen & housewares,4.166667,0.559983,4.166667,positive,positive,"{'points': 3.1974522292993632, 'wife': 3.14345..."
10 2spd bo indout fan,1,electronics,4.000000,0.996400,5.000000,positive,positive,"{'way': 3.331992850759607, 'size': 3.361313868..."
10 faces of sonny chiba (10pc),2,dvd,5.000000,0.942050,5.000000,positive,positive,"{'picture': 3.3452380952380953, 'influences': ..."
10 minute solution,23,dvd,4.565217,0.848470,4.826087,positive,positive,"{'workouts': 3.1869158878504673, 'moves': 3.27..."
...,...,...,...,...,...,...,...,...
zyliss soft skin peeler,6,kitchen & housewares,4.500000,0.571550,4.333333,positive,positive,{'tomatoes': 3.2142857142857144}
zyliss susi deluxe garlic press,8,kitchen & housewares,4.750000,0.734988,4.625000,positive,positive,"{'need': 3.165909090909091, 'price': 3.4431818..."
zyliss swivel peeler,5,kitchen & housewares,4.800000,0.876040,5.000000,positive,positive,"{'recommend': 3.3304721030042916, 'getting': 3..."
zyliss ypeeler white,2,kitchen & housewares,5.000000,0.854500,5.000000,positive,positive,"{'thing': 3.2267384916748285, 'peelers': 3.0}"
zymox otic with 10 hydrocortisone 125 oz bottle,8,kitchen & housewares,5.000000,0.768800,4.875000,positive,positive,"{'ears': 3.2162162162162162, 'vets': 3.0, 'dog..."

In [9]:
# reset index to create a new column with the old index values
df_grouped.reset_index(inplace=True)
df_grouped

,product_name,count,product_type,rating,normal_sentiment_score,rating_by_normal_sentiment,initial_sentiment,normal_sentiment,aspect_ratings
0,089 deep stainless steel mixing bowl set 3pc,1,kitchen & housewares,5.000000,0.680100,5.000000,positive,positive,{'serve': 3.1818181818181817}
1,1 doz red roses,6,kitchen & housewares,4.166667,0.559983,4.166667,positive,positive,"{'points': 3.1974522292993632, 'wife': 3.14345..."
2,10 2spd bo indout fan,1,electronics,4.000000,0.996400,5.000000,positive,positive,"{'way': 3.331992850759607, 'size': 3.361313868..."
3,10 faces of sonny chiba (10pc),2,dvd,5.000000,0.942050,5.000000,positive,positive,"{'picture': 3.3452380952380953, 'influences': ..."
4,10 minute solution,23,dvd,4.565217,0.848470,4.826087,positive,positive,"{'workouts': 3.1869158878504673, 'moves': 3.27..."
...,...,...,...,...,...,...,...,...,...
12058,zyliss soft skin peeler,6,kitchen & housewares,4.500000,0.571550,4.333333,positive,positive,{'tomatoes': 3.2142857142857144}
12059,zyliss susi deluxe garlic press,8,kitchen & housewares,4.750000,0.734988,4.625000,positive,positive,"{'need': 3.165909090909091, 'price': 3.4431818..."
12060,zyliss swivel peeler,5,kitchen & housewares,4.800000,0.876040,5.000000,positive,positive,"{'recommend': 3.3304721030042916, 'getting': 3..."
12061,zyliss ypeeler white,2,kitchen & housewares,5.000000,0.854500,5.000000,positive,positive,"{'thing': 3.2267384916748285, 'peelers': 3.0}"
12062,zymox otic with 10 hydrocortisone 125 oz bottle,8,kitchen & housewares,5.000000,0.768800,4.875000,positive,positive,"{'ears': 3.2162162162162162, 'vets': 3.0, 'dog..."

In [10]:
# Saving the intermediate dataframe for further reference
df_grouped.to_excel(r"C:\Users\shree\OneDrive\Desktop\IR Project Working Directory\final_grouped_dataframe.xlsx")